name: Docker image building

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  building:
    strategy:
      matrix:
        version: [whatever, otherstuff]
    name: Docker building
    runs-on: ubuntu-latest

    steps:
      outputs:
        link: ${{ steps.publish.outputs.link }}
        logs: ${{ steps.publish.outputs.logs }}
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Link
        id: publish
        run: | 
          echo "link=thisisthelink" >> $GITHUB_OUTPUT
          echo "logs=thisarelogs" >> $GITHUB_OUTPU
      
      - name: Echo link
        run: echo ${{ step.publish.outputs.link }}
      - name: Echo logs
        run: echo ${{ step.publish.outputs.logs }}