name: Docker image building

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  building:
    strategy:
      matrix:
        version: [whatever, otherstuff]
    name: Docker building
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Extract tag name
        run: echo "test={{version}}" >> $GITHUB_OUTPUT
      
      - name: Echo output
        run: echo $GITHUB_OUTPUT